name: "Build Material Maker"

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

env:
  GODOT_VERSION: 4.7.2
  GODOT_SUB: stable
  GODOT_DOWNLOAD_DIR: https://github.com/godotengine/godot-builds/releases/download/4.7.2-stable
  EXPORT_NAME: material_maker
  MM_RELEASE: 1_7

jobs:
  export_android:
    name: Export Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Setup JDK ☕️
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: 'platform-tools'
      - name: Setup environment 🔧
        run: |
          cp -f material_maker/theme/default_theme_icons.svg material_maker/theme/default_theme_icons_export.svg
          export GODOT_VERSION=${GODOT_VERSION}
          export EXPORT_NAME=material_maker
      - name: Download and extract Godot and export templates 💾
        run: |
          wget ${GODOT_DOWNLOAD_DIR}/Godot_v${GODOT_VERSION}-${GODOT_SUB}_linux.x86_64.zip
          unzip -a Godot_v${GODOT_VERSION}-${GODOT_SUB}_linux.x86_64.zip
          wget ${GODOT_DOWNLOAD_DIR}/Godot_v${GODOT_VERSION}-${GODOT_SUB}_export_templates.tpz
          unzip -a Godot_v${GODOT_VERSION}-${GODOT_SUB}_export_templates.tpz
          mkdir -v -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.${GODOT_SUB}
          mv ./templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.${GODOT_SUB}
          mkdir -v -p ./build/android
      - name: Export Android debug (apk)
        run: |
          ./Godot_v${GODOT_VERSION}-${GODOT_SUB}_linux.x86_64 --headless --export-debug "Android" ./build/android/${EXPORT_NAME}_${MM_RELEASE}_android_debug.apk
      - name: Export Android release (apk)
        env:
          GODOT_ANDROID_KEYSTORE_RELEASE_PATH: "/tmp/release.keystore"
          GODOT_ANDROID_KEYSTORE_RELEASE_USER: ${{ secrets.KEY_ALIAS }}
          GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > /tmp/release.keystore
          ./Godot_v${GODOT_VERSION}-${GODOT_SUB}_linux.x86_64 --headless --export-release "Android" ./build/android/${EXPORT_NAME}_${MM_RELEASE}_android_release.apk
      - name: Upload Android debug artifact
        uses: actions/upload-artifact@v7
        with:
          name: android_debug_snapshot
          path: ./build/android/${{ env.EXPORT_NAME }}_${{ env.MM_RELEASE }}_android_debug.apk
      - name: Upload Android release artifact
        uses: actions/upload-artifact@v7
        with:
          name: android_release_snapshot
          path: ./build/android/${{ env.EXPORT_NAME }}_${{ env.MM_RELEASE }}_android_release.apk
